using System.Runtime.Versioning;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using VisitorManagementSystem.Api.Application.Models.Licensing;
using VisitorManagementSystem.Api.Application.Services.Licensing;
using VisitorManagementSystem.Api.Domain.Enums;

namespace VisitorManagementSystem.Api.Infrastructure.Services.Licensing;

[SupportedOSPlatform("windows")]
public class LicenseValidatorService : ILicenseValidatorService
{
    // ─── EMBEDDED PUBLIC KEY ────────────────────────────────────────────────
    // Generated by: vms-license-tool keygen --output ./keys --password <pw>
    // Replace this placeholder with the content of PublicKeyConst.cs after running keygen.
    // NEVER replace with the private key. NEVER load from configuration or database.
    private const string VmsPublicKey =
        "-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA1aIGbpZsLKTMet6OGWRj\nMo8TL9p0TVTOJAOtolF0PTZvYI+8JoiTI6J/YjBSgtcnKsatO+giwjLZj+82Ic8N\nGZt0s32ikJiEGmtekd06KhfxJL6DccC7r0We5T3MbGcYTmSwSm9SK7+c6YSQfw5H\nFlqBuioN3xgM5JEF8l5G2lTfiXU47YTjshrUdb7YgX/aQIPRFJk0H3A2pHPhbY+d\nkRSF1w8E1K5WL2/dJH7uk0Kg+y+HxzT9ze7EQ7DVuLgsn6RL4H5cvyA8kUqm/ru5\nhfY+UruXZ/j1oJLQ77wwOISic1uaS/UVTixOdIdzILQLPTt0tFBbjCpaUeLeZMK/\n4NzmrddgQZJstvurXcRcXdm434L7n7l/sSmgum+8botaRb0WuGV9PPTxg8V5zsH+\n9a0iD46ChMfCBgI5Q98pm75yOIGAdYRysSN6oYc185EJ8t4JU45AhmuPHjt5G6m6\ncFa1IUuIvIWxZoLqSNyl57GJ9sP3+DBR390B3b9hOoX0ZAWK3UPBOycWw+JjdJaz\nezTySvD3dZ829x1KeZ3AQKTMHegeKmv64TsCkcGibHcpZU7f80WJPAGgZO+nswZM\nF7yZhMccGccfA7UhBcIcbJCbm1N3eo6UmfFrUQf6T/3tVAEqR5cRi1YOdKT3gZFk\nUHIZgx7BHN+jmdC/W3k0LjECAwEAAQ==\n-----END PUBLIC KEY-----";

    // ────────────────────────────────────────────────────────────────────────

    private readonly ILicenseStorageService _storage;
    private readonly IMachineFingerprintService _fingerprint;
    private readonly IHostEnvironment _environment;
    private readonly ILogger<LicenseValidatorService> _logger;

    private LicenseValidationResult _cachedResult = LicenseValidationResult.NotActivated();
    private readonly SemaphoreSlim _validateLock = new(1, 1);

    public LicenseValidatorService(
        ILicenseStorageService storage,
        IMachineFingerprintService fingerprint,
        IHostEnvironment environment,
        ILogger<LicenseValidatorService> logger)
    {
        _storage = storage;
        _fingerprint = fingerprint;
        _environment = environment;
        _logger = logger;
    }

    public LicenseValidationResult GetCachedResult() => _cachedResult;

    public void InvalidateCache() => _cachedResult = LicenseValidationResult.NotActivated();

    public async Task<LicenseValidationResult> ValidateCurrentLicenseAsync(CancellationToken ct = default)
    {
        // Dev mode: full bypass
        if (_environment.IsDevelopment())
        {
            _cachedResult = LicenseValidationResult.DevMode();
            return _cachedResult;
        }

        await _validateLock.WaitAsync(ct);
        try
        {
            var result = await RunAllChecksAsync(ct);
            _cachedResult = result;
            return result;
        }
        finally
        {
            _validateLock.Release();
        }
    }

    public async Task<LicenseValidationResult> ActivateLicenseAsync(byte[] licenseFileBytes, CancellationToken ct = default)
    {
        LicensePayload? payload;
        try
        {
            var json = Encoding.UTF8.GetString(licenseFileBytes);
            payload = System.Text.Json.JsonSerializer.Deserialize<LicensePayload>(json,
                new System.Text.Json.JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        }
        catch
        {
            return LicenseValidationResult.Failure(LicenseStatus.Invalid, "License file is not valid JSON.");
        }

        if (payload == null)
            return LicenseValidationResult.Failure(LicenseStatus.Invalid, "License file is empty.");

        // Run signature + hardware checks before storing
        var tempResult = await ValidatePayloadAsync(payload, ct);
        if (!tempResult.IsValid)
            return tempResult;

        // Store (DPAPI + Registry + DB)
        await _storage.StoreLicenseAsync(payload, ct);

        var scores = _fingerprint.ScoreAgainstLicense(payload.MachineFingerprint);
        await _storage.UpdateDatabaseRecordAsync(payload, scores, null, ct);

        _cachedResult = tempResult;
        _logger.LogInformation("License activated for {Email} (ID: {LicenseId}, Type: {Type})",
            payload.CustomerEmail, payload.LicenseId, payload.LicenseType);

        return tempResult;
    }

    public async Task DeactivateAsync(CancellationToken ct = default)
    {
        await _storage.ClearLicenseAsync(ct);
        _cachedResult = LicenseValidationResult.NotActivated();
        _logger.LogInformation("License deactivated.");
    }

    // ── Private ──────────────────────────────────────────────────────────────

    private async Task<LicenseValidationResult> RunAllChecksAsync(CancellationToken ct)
    {
        // Check 1: File exists
        if (!_storage.LicenseFileExists())
            return LicenseValidationResult.NotActivated();

        // Check 2: Load from DPAPI file
        var payload = await _storage.LoadLicenseAsync(ct);
        if (payload == null)
            return LicenseValidationResult.Failure(LicenseStatus.Tampered, "License file could not be decrypted.");

        return await ValidatePayloadAsync(payload, ct);
    }

    private async Task<LicenseValidationResult> ValidatePayloadAsync(LicensePayload payload, CancellationToken ct)
    {
        // Check 3: RSA-PSS signature
        if (!VerifySignature(payload))
        {
            _logger.LogWarning("License signature invalid for {LicenseId}", payload.LicenseId);
            return LicenseValidationResult.Failure(LicenseStatus.Tampered, "License signature is invalid. File may have been tampered with.");
        }

        // Check 4: Version and required fields
        if (payload.Version != 1 || string.IsNullOrEmpty(payload.LicenseId))
            return LicenseValidationResult.Failure(LicenseStatus.Invalid, "License format is not supported.");

        // Check 5: License type validity
        if (!Enum.TryParse<LicenseType>(payload.LicenseType, true, out var licenseType))
            return LicenseValidationResult.Failure(LicenseStatus.Invalid, $"Unknown license type: {payload.LicenseType}");

        if (licenseType == LicenseType.Disabled)
            return LicenseValidationResult.Failure(LicenseStatus.Revoked, "This license has been disabled.");

        if (licenseType == LicenseType.Revoked)
            return LicenseValidationResult.Failure(LicenseStatus.Revoked, "This license has been revoked.");

        // Check 6: Time validity
        var now = DateTime.UtcNow;
        if (now < payload.NotBefore)
            return LicenseValidationResult.Failure(LicenseStatus.Invalid, "License is not yet valid.");

        if (now > payload.ExpiresAt)
        {
            _logger.LogWarning("License {LicenseId} expired at {ExpiresAt}", payload.LicenseId, payload.ExpiresAt);
            return LicenseValidationResult.Failure(LicenseStatus.Expired,
                $"License expired on {payload.ExpiresAt:yyyy-MM-dd}. Please renew.");
        }

        // Check 7: Machine fingerprint (only if component hashes are present)
        bool[] componentScores = Array.Empty<bool>();
        if (payload.MachineFingerprint.ComponentHashes.Length > 0)
        {
            componentScores = _fingerprint.ScoreAgainstLicense(payload.MachineFingerprint);
            int matchCount = componentScores.Count(s => s);
            if (matchCount < payload.MachineFingerprint.RequiredMatches)
            {
                _logger.LogWarning("Hardware mismatch for {LicenseId}: {MatchCount}/{Required} components matched",
                    payload.LicenseId, matchCount, payload.MachineFingerprint.RequiredMatches);
                return LicenseValidationResult.Failure(LicenseStatus.HardwareMismatch,
                    $"License is bound to a different machine ({matchCount}/{payload.MachineFingerprint.RequiredMatches} hardware components match).");
            }
        }
        else if (!string.IsNullOrEmpty(payload.MachineFingerprint.FullHash))
        {
            // Full-hash-only mode (tool issued without per-component hashes)
            var currentFp = _fingerprint.GetDisplayFingerprint();
            if (!string.Equals(currentFp, payload.MachineFingerprint.FullHash, StringComparison.OrdinalIgnoreCase))
            {
                _logger.LogWarning("Hardware fingerprint mismatch for {LicenseId}", payload.LicenseId);
                return LicenseValidationResult.Failure(LicenseStatus.HardwareMismatch,
                    "License is bound to a different machine.");
            }
        }

        // Check 8: Registry integrity (tamper cross-check)
        var registryOk = await _storage.VerifyRegistryIntegrityAsync(payload);
        if (!registryOk)
        {
            _logger.LogWarning("Registry integrity check failed for {LicenseId} — possible tamper", payload.LicenseId);
            // Log but don't hard-fail if Registry key doesn't exist (e.g. service account without HKLM write).
            // Only fail if Registry key EXISTS but checksum is wrong (definitive tamper evidence).
        }

        // Check 9: Database revocation
        var isRevoked = await _storage.IsDatabaseRevokedAsync(payload.LicenseId, ct);
        if (isRevoked)
        {
            _logger.LogWarning("License {LicenseId} is marked as revoked in database", payload.LicenseId);
            return LicenseValidationResult.Failure(LicenseStatus.Revoked, "This license has been revoked.");
        }

        // All checks passed — update DB record
        await _storage.UpdateDatabaseRecordAsync(payload, componentScores, null, ct);

        return LicenseValidationResult.Success(payload, componentScores);
    }

    private static bool VerifySignature(LicensePayload payload)
    {
        if (VmsPublicKey.StartsWith("REPLACE_WITH_"))
        {
            // Public key not yet configured — only happens during initial development setup.
            // This will cause ALL license validation to fail, which is correct behavior
            // until the developer runs `keygen` and embeds the real public key.
            return false;
        }

        try
        {
            using var rsa = RSA.Create();
            rsa.ImportFromPem(VmsPublicKey);
            var canonical = Encoding.UTF8.GetBytes(payload.ToCanonicalJson());
            var signature = Convert.FromBase64String(payload.Signature);
            return rsa.VerifyData(canonical, signature, HashAlgorithmName.SHA256, RSASignaturePadding.Pss);
        }
        catch
        {
            return false;
        }
    }
}
